### USPS OAuth Token
POST https://api.usps.com/oauth2/v3/token
content-type: application/json

{
  "grant_type": "client_credentials",
  "client_id": "",
  "client_secret": ""
}


### Register Address
POST https://api.richcrm.org/v1/utils/address/register
content-type: application/json

{
    "addressLine1": "130 W Third St",
    "addressLine2": "1203",
    "city": "New York",
    "state": "NY",
    "zipCode": "10012"
}

### Delete Address
POST http://localhost:3001/v1/utils/address/delete
content-type: application/json

{
    "addressId": "New York NY 10012-1296"
}



### Get All Address
GET http://localhost:3001/v1/utils/address/all


### Get Address by Id
POST http://localhost:3001/v1/utils/address/query/id
content-type: application/json

{
    "addressId": "New York NY 10012-1296"
}


### Send Email via SES
POST https://api.richcrm.org/v1/utils/email/send
content-type: application/json

{
    "toAddresses": ["verkho404@gmail.com"],
    "ccAddresses": [],
    "templateTitle": "[IMPORTANT] Closing Confirmation send to all parties",
    "templateContent": "Hi All, \n\n\nThis is to confirm closing for the above-referenced matter for **2024-07-20T20:24:24.740Z**. Closing will be held at our office, 37-01 Main Street, #309, Flushing, NY \n\n\nXXX, please forward adjustments, checklist, and payoff. \n\n\nXXX, please forward the final title bill. \n\n\nXXX please forward the net and when it becomes available. \n\n\nXXX/XXX, please forward your commission bill. \n\n\nThank you all!\n\nSincerely,\n\nMG Law Group"
}