### Register Client
POST https://api.richcrm.org/v1/client/register
content-type: application/json

{
    "clientId": "d5dbbca5-808c-4df8-b51b-b09b1cb595bd",
    "clientType": 0,
    "firstName": "John",
    "lastName": "Doe",
    "cellNumber": "1234567891",
    "email": "john.doe@hotmail.com"
}

### Get All Clients
GET http://localhost:3001/v1/client/all

### Query Clients
POST http://localhost:3001/v1/client/query
content-type: application/json

{
    "keyword": "John"
}


### Query Clients by Type
POST http://localhost:3001/v1/client/query/type
content-type: application/json

{
    "clientType": 1
}


### Query Clients by Id
POST http://localhost:3001/v1/client/query/id
content-type: application/json

{
    "clientId": "738ffc97-299b-423a-b759-2116a402b18d"
}


### Get Client
GET http://localhost:3001/v1/client/738ffc97-299b-423a-b759-2116a402b18d


### Update Client
POST http://localhost:3001/v1/client/update
content-type: application/json

{
    "clientId": "738ffc97-299b-423a-b759-2116a402b18d",
    "clientType": 3,
    "title": 1,
    "firstName": "Jean",
    "lastName": "Dean",
    "gender": 1,
    "cellNumber": "1234567891",
    "workNumber": "1234567890",
    "email": "jean.dean@hotmail.com",
    "wechatAccount": "jean.dean", 
    "dob": "1990-01-01", 
    "attorneyId": 1, 
    "bankAttorneyId": 1, 
    "ssn": "123-45-6789",
    "addressId": "New York NY 10012-1296"
}

### Delete Client
POST http://localhost:3001/v1/client/delete
content-type: application/json

{
    "clientId": "04230e7a-2c5d-426e-8d7f-a548892713e4"
}