### Register Client
POST http://localhost:3001/v1/client/register
content-type: application/json

{
    "clientType": 1,
    "firstName": "John",
    "lastName": "Doe",
    "cellNumber": "1234567891",
    "email": "john.doe@hotmail.com"
}

### Query Clients
POST http://localhost:3001/v1/client/query
content-type: application/json

{
    "keyword": "John"
}


### Query Clients by Type
POST http://localhost:3001/v1/client/query/type
content-type: application/json

{
    "clientType": 1
}


### Get Client
GET http://localhost:3001/v1/client/40c34a24-706a-4abb-98b2-b844f29cef1e


### Update Client
POST http://localhost:3001/v1/client/update
content-type: application/json

{
    "clientId": "40c34a24-706a-4abb-98b2-b844f29cef1e",
    "clientType": 3,
    "title": 1,
    "firstName": "Jean",
    "lastName": "Dean",
    "gender": 1,
    "cellNumber": "1234567890",
    "workNumber": "1234567890",
    "email": "jean.dean@hotmail.com",
    "wechatAccount": "jean.dean", 
    "dob": "1990-01-01", 
    "attorneyId": 1, 
    "bankAttorneyId": 1, 
    "ssn": "123-45-6789",
    "addressId": "1600 AMPHITHEATRE PKWY, MOUNTAIN VIEW, CA 94043-1351 US"
}

### Delete Client
POST http://localhost:3001/v1/client/delete
content-type: application/json

{
    "clientId": "04230e7a-2c5d-426e-8d7f-a548892713e4"
}