### USPS OAuth Token
POST https://api.usps.com/oauth2/v3/token
content-type: application/json

{
  "grant_type": "client_credentials",
  "client_id": "",
  "client_secret": ""
}


### Register Address
POST http://localhost:3001/v1/utils/address/register
content-type: application/json

{
    "addressLine1": "22 Chapel St",
    "city": "Brooklyn",
    "state": "NY",
    "zipCode": "11201"
}

### Delete Address
POST http://localhost:3001/v1/utils/address/delete
content-type: application/json

{
    "addressId": "22 CHAPEL ST, BROOKLYN, NY 11201-1945 US"
}



### Get All Address
GET http://localhost:3001/v1/utils/address/all

