### Create template
POST http://localhost:3001/v1/template/create
content-type: application/json

{
    "templateTitle": "Default Template",
    "templateContent": "Dear XXX,\n\n\n\n\nSincerely,\n\nMG Law Group"
}

# {
#     "templateTitle": "[IMPORTANT] FEK Notice to Purchaser",
#     "templateContent": "Hi %(clientObj.FirstName)s, \n\n\nAttached is a copy of the fully executed contract that we received from the seller’s attorney.\n\nPLEASE KEEP THESE IMPORTANT DATES IN MIND: \n\nCLOSING DATE: The closing date in the contract is **ON OR ABOUT %(caseObj.ClosingDate)s**.  This means the closing can be anytime between **%(caseObj.ClosingDate)s TO %(caseObj.ClosingDate)s** if all parties agree.\n\nMORTGAGE CONTINGENCY DATE:  The mortgage commitment must be obtained by **%(caseObj.MortgageContingencyDate)s**. If you cannot obtain the commitment by **%(caseObj.MortgageContingencyDate)s** please let me know immediately so I can request an extension of this date.\n\nRATE LOCKS:  If the client decides to \"lock-in\" an interest rate PLEASE MAKE SURE THE RATE LOCK IS GOOD THROUGH **%(caseObj.ClosingDate)s**.\n\n\nPlease let me know if anything else is needed.\n\nThank you!\n\n\nSincerely,\n\nMG Law Group"
# }


### Get template by template Title
POST http://localhost:3001/v1/template/read
content-type: application/json

{
    "templateTitle": "[IMPORTANT] FEK Notice to Purchaser"
}


### Update template by template Title
POST http://localhost:3001/v1/template/update
content-type: application/json

{
    "templateTitle": "[IMPORTANT] FEK Notice to Purchaser",
    "templateContent": "Hi %(clientObj.FirstName)s, \n\n\nAttached is a copy of the fully executed contract that we received from the seller’s attorney.\n\nPLEASE KEEP THESE IMPORTANT DATES IN MIND: \n\nCLOSING DATE: The closing date in the contract is **ON OR ABOUT %(caseObj.ClosingDate)s**.  This means the closing can be anytime between **%(caseObj.ClosingDate)s TO %(caseObj.ClosingDate)s** if all parties agree.\n\nMORTGAGE CONTINGENCY DATE:  The mortgage commitment must be obtained by **%(caseObj.MortgageContingencyDate)s**. If you cannot obtain the commitment by **%(caseObj.MortgageContingencyDate)s** please let me know immediately so I can request an extension of this date.\n\nRATE LOCKS:  If the client decides to \"lock-in\" an interest rate PLEASE MAKE SURE THE RATE LOCK IS GOOD THROUGH **%(caseObj.ClosingDate)s**.\n\n\nPlease let me know if anything else is needed.\n\nThank you!\n\n\nSincerely,\n\nMG Law Group"
}


### Delete template by template Title
POST http://localhost:3001/v1/template/delete
content-type: application/json

{
    "templateTitle": "[Notice] Your account has been created"
}


### Fill template with data
POST http://localhost:3001/v1/template/fill
content-type: application/json

{
    "templateTitle":"[IMPORTANT] FEK Notice to Purchaser",
    "data":{
        "clientObj":{
            "clientId":"b00d0c51-ed29-4d4e-9555-758a63e510a2",
            "clientType":0,
            "title":0,
            "firstName":"Mackenzie",
            "lastName":"Gutmann",
            "gender":0,
            "email":"client@client.com",
            "addressId":"Brooklyn NY 11201-1945#709",
            "addressLine1":"22 Chapel St # 709",
            "addressLine2":"709",
            "city":"Brooklyn",
            "state":"NY",
            "zipCode":"11201","plus4":"1945"},
        "caseObj":{
            "caseId":"563f390e-1c1b-4645-8ecc-f5887c211cc6",
            "creatorId":"test1@gmail.com",
            "premisesId":"fd3bb1b6-4e8c-4ebf-9ae6-f7562e29f00a",
            "premisesName":"3701 Clay Products Dr_Anchorage AK 99517-1011",
            "stage":0,
            "caseStatus":0,
            "stageId":"eba945f6-c1e7-4581-883b-14466ca4a326",
            "caseType":0,
            "clientType":0,
            "clientId":"b00d0c51-ed29-4d4e-9555-758a63e510a2",
            "clientName":"Gutmann, Mackenzie",
            "createAt":"2024-10-08T05:02:29.593Z",
            "closingDate":"2024-10-23T03:30:00.000Z","additionalClients":["6e1dfd67-ca35-41c1-9d31-180509a92fc5"],"contacts":[],"additionalOrganizations":[]}}}