### Create Case
POST http://localhost:3001/v1/case/create
content-type: application/json

{
    "premisesId": "7a42576c-ecee-4828-bc56-fc7ed49488ed",
    "creatorId": "eden.wu@richtechailab.com",
    "stage": 0,
    "caseType": 1,
    "sellerId": "123-45-6789",
    "buyerId": ""
}


### Read Case
GET http://localhost:3001/v1/case/0_f3117eaa-e3a7-4b3e-88fb-37a8741a181e_b394ec2a-24c0-4913-b065-09bcaecbeb9a


### Read All Cases by Creator
POST http://localhost:3001/v1/case/all
content-type: application/json

{
    "creatorId": "eden.wu@richtechailab.com"
}



### Update Case
POST http://localhost:3001/v1/case/update
content-type: application/json

{
    "caseId": "1_e9a51f4a-ea7c-443d-9d66-e9d62bc41308_afa4ed13-f510-4edb-905b-ce9c12280ccc",
    "creatorId": "eden.wu@richtechailab.com",
    "stage": 4,
    "closingDate": "2024-07-20T20:24:24.740Z"
}


### Delete Case
POST http://localhost:3001/v1/case/delete
content-type: application/json

{
    "caseId": "1_e9a51f4a-ea7c-443d-9d66-e9d62bc41308_afa4ed13-f510-4edb-905b-ce9c12280ccc"
}