### Create Task
POST http://localhost:3001/v1/task/create
content-type: application/json

{
    "stageId": "ab4c7c67-66c7-483d-a34f-d3afdbe17086",
    "taskType": 1,
    "name": "Customized Taskkkk",
    "status": 1,
    "templates": [
        {"templateTitle": "Test Email Template 1"},
        {"templateTitle": "Test Email Template 2"}
    ]
}

### Get Task by Task ID
GET http://localhost:3001/v1/task/c84bcf18-eba0-4f6b-9d78-76a856ed58e8


### Update Task by Task ID
POST http://localhost:3001/v1/task/update
content-type: application/json

{
    "taskId": "c84bcf18-eba0-4f6b-9d78-76a856ed58e8",
    "status": 2,
    "templates": [
        {"templateTitle": "Test Email Template 1"},
        {"templateTitle": "Test Email Template 3"},
        {"templateTitle": "Test Email Template 4"}
    ]
}

### Delete Task by Task ID
POST http://localhost:3001/v1/task/delete
content-type: application/json

{
    "taskId": "54ed26b0-bc16-4753-85d7-9a49d4d2a4a9"
}
