### Create Case
POST http://localhost:3001/v1/case/create
content-type: application/json

{
    "premisesId": "8e5ac210-7c07-4dde-8ed2-f0d2b9f23699",
    "creatorId": "test1@gmail.com",
    "stage": 0,
    "caseType": 1,
    "sellerId": "738ffc97-299b-423a-b759-2116a402b18d",
    "buyerId": ""
}


### Read Case
GET http://localhost:3001/v1/case/8f84c1e4-c3ee-405d-a4d7-fc54ec3ce503


### Read All Cases by Creator
POST http://localhost:3001/v1/case/all
content-type: application/json

{
    "creatorId": "test1@gmail.com",
    "closed": false
}



### Update Case
POST http://localhost:3001/v1/case/update
content-type: application/json

{
    "caseId": "1_123-45-6789_7a42576c-ecee-4828-bc56-fc7ed49488ed",
    "creatorId": "eden.wu@richtechailab.com",
    "stage": 4,
    "closeAt": "2024-07-20T20:24:24.740Z",
    "closingDate": "2024-07-20T20:24:24.740Z",
    "mortgageContingencyDate": "2024-07-20T20:24:24.740Z"
}


### Delete Case
POST http://localhost:3001/v1/case/delete
content-type: application/json

{
    "caseId": "1_123-45-6789_7a42576c-ecee-4828-bc56-fc7ed49488ed"
}