### Create Stage
POST http://localhost:3001/v1/stage/create
Content-Type: application/json

{
    "stageType": 1,
    "caseId": "0_f3117eaa-e3a7-4b3e-88fb-37a8741a181e_b394ec2a-24c0-4913-b065-09bcaecbeb9a"
}


### Get Stage by Case ID and Stage Type
GET http://localhost:3001/v1/stage/0_f3117eaa-e3a7-4b3e-88fb-37a8741a181e_b394ec2a-24c0-4913-b065-09bcaecbeb9a/1


### Update Stage by Stage ID
POST http://localhost:3001/v1/stage/update
Content-Type: application/json

{
    "stageId": "d3d9c867-a83e-454b-a9c1-9c8abdc37811",
    "stageStatus": 2,
    "newTask": "11223344"
}

### Delete Stage by Stage ID
POST http://localhost:3001/v1/stage/delete
Content-Type: application/json

{
    "stageId": "1e4e3945-f7c7-45c2-a26a-f81b63a85d4a"
}
