### Create Stage
POST http://localhost:3001/v1/stage/create
Content-Type: application/json

{
    "stageType": 2,
    "caseId": "5debf678-7b96-49ff-a700-f8f8d6b9edec"
}

### Get Stage by Stage ID
GET http://localhost:3001/v1/stage/59f4581b-4360-4f2a-be37-b516cfd330ff

### Get Stage by Case ID and Stage Type
GET http://localhost:3001/v1/stage/048c4235-183f-4061-8ff5-ab75d4dbc625/2


### Update Stage by Stage ID
POST http://localhost:3001/v1/stage/update
Content-Type: application/json

{
    "stageId": "f75e0782-2515-4df3-8449-593a6e6dd726",
    "stageStatus": 1,
    "newTask": "f88d45df-b6f6-4d87-99e8-8ffc789e9834"
}

### Delete Stage by Stage ID
POST http://localhost:3001/v1/stage/delete
Content-Type: application/json

{
    "stageId": "2762c001-057b-44e9-bfe9-177ded53e626"
}


### Delete All Stages by Case ID
POST http://localhost:3001/v1/stage/delete/all
Content-Type: application/json

{
    "caseId": "0_e9a51f4a-ea7c-443d-9d66-e9d62bc41308_afa4ed13-f510-4edb-905b-ce9c12280ccc"
}
