### Register Premises
POST http://localhost:3001/v1/premises/register
content-type: application/json

{
    "name": "Test Premises #1",
    "addressId": "Pompano Beach FL 33069-1300",
    "propertyType": 3
}


### Read Premises by Id
POST http://localhost:3001/v1/premises/query/id
content-type: application/json

{
    "premisesId": "1820 NW 21st St #undefined CONDO"
}


### Read Premises by AddressId
POST http://localhost:3001/v1/premises/query/address
content-type: application/json

{
    "addressId": "1600 AMPHITHEATRE PKWY, MOUNTAIN VIEW, CA 94043-1351 US"
}

### Update Premises
POST http://localhost:3001/v1/premises/update
content-type: application/json

{
    "premisesId": "1820 NW 21st St # COMMERCIAL",
    "name": "Test Premises #1",
    "addressId": "1600 AMPHITHEATRE PKWY, MOUNTAIN VIEW, CA 94043-1351 US",
    "block": 1,
    "lot": 1,
    "section": 1,
    "vacantAtClosing": true,
    "subjectToTenancy": false,
    "hoa": true,
    "parkingSpaces": 2,
    "maintenanceFee": 100,
    "maintenanceFeePer": 1,
    "assessments": 100,
    "assessmentsPaidById": "123456",
    "managingCompany": "RichCRM",
    "isTwoFamily": false
}


### Delete Premises
POST http://localhost:3001/v1/premises/delete
content-type: application/json

{
    "premisesId": "1820 NW 21st St # COMMERCIAL"
}