### Create Case
POST http://localhost:3001/v1/case/create
content-type: application/json

{
    "premisesId": "130 W 3rd St # 1203 COMMERCIAL",
    "creatorId": "eden.wu@richtechailab.com",
    "stage": 0,
    "caseType": 0,
    "sellerId": "",
    "buyerId": "738ffc97-299b-423a-b759-2116a402b18d"
}


### Read Case
GET http://localhost:3001/v1/case/37133c20-8e37-42e6-98cd-d2422df2eefd


### Read All Cases by Creator
POST http://localhost:3001/v1/case/all
content-type: application/json

{
    "creatorId": "test1@gmail.com",
    "closed": false
}



### Update Case
POST http://localhost:3001/v1/case/update
content-type: application/json

{
    "caseId": "1_123-45-6789_7a42576c-ecee-4828-bc56-fc7ed49488ed",
    "creatorId": "eden.wu@richtechailab.com",
    "stage": 4,
    "closeAt": "2024-07-20T20:24:24.740Z",
    "closingDate": "2024-07-20T20:24:24.740Z",
    "mortgageContingencyDate": "2024-07-20T20:24:24.740Z"
}


### Delete Case
POST http://localhost:3001/v1/case/delete
content-type: application/json

{
    "caseId": "1_123-45-6789_7a42576c-ecee-4828-bc56-fc7ed49488ed"
}